export const data = {
  recentPosts: "ph:newspaper-duotone",
  projects: "ph:acorn-duotone",
  techStack: "ph:code-duotone",
  friends: "ph:users-duotone",
  words: "ph:align-left-bold",
  time: "ph:timer-bold",
  link: "ph:link-bold",
  calendar: "ph:calendar-blank-duotone",
  category: "ph:book-bookmark-duotone",
  tag: "ph:tag-duotone",
  new: "ph:folder-notch-duotone",
  open: "ph:link-duotone",
  edit: "ph:pen-duotone",
  delete: "ph:trash-duotone",
  moment: "ph:clock-duotone",
  musics: "ph:music-notes-duotone",
  singer: "ph:microphone-stage-duotone",
  negative: "ph:smiley-sad-duotone",
  unableFriends: "ph:wifi-slash-duotone",
  photos: "ph:picture-in-picture-duotone",
  about: "ph:info-duotone",
  tasks: "ph:list-checks-duotone",
  taskComplete: "ph:check-circle-fill",
  taskNotComplete: "ph:circle",
  schedule: "ph:calendar-blank-duotone",
};
